"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['giphy.gif','invoice_template.docx','doc_gen.py','journeys_data.csv','recent_files_stored.csv']
OPTIONS = {
    'packages': [],
    'iconfile': 'icon.jpg',
    'plist': {
        'CFBundleDevelopmentRegion': 'English',
        'CFBundleIdentifier': 'com.ezoty.invoice_demo_generator',
        'CFBundleVersion': "1.0.0",
        'NSHumanReadableCopyright': u"Copyright 2023, Ezoty, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
